pythonweb/moviepoll/urls.py
from django.urls import path
from . import views


app_name = 'moviepoll'
urlpatterns = [
    path('', views.index, name='index'),
    path('poll/', views.poll, name='poll'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result', views.result, name='result'),
]

pythonweb/pythonweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include("moviepoll.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

pythonweb/moviepoll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pythonweb/moviepoll/views.py
from django.shortcuts import get_object_or_404, render
from .models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    return render(request,
                  'moviepoll/index.html',
                  )


def poll(request):
    return render(request,
                  'moviepoll/poll.html',
                  )


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,
                  'moviepoll/detail.html',
                  {'question': question},
                 )


def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'moviepoll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('moviepoll:detail', args=[question.id]))

pythonweb/moviepoll/templates/moviepoll/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Intek Friday Movie Night</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'moviepoll/style.css' %}">
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'moviepoll:index' %}">
          <img src="{% static 'moviepoll/intek-logo.png' %}" width=50px class="img-fluid" alt="intek-logo"> Intek Institute
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'moviepoll:index' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdown" data-toggle="dropdown">Polls</a>
              <div class="dropdown-menu">
                {% for question in question_list %}
                    <a class="dropdown-item" href="{% url 'moviepoll:detail' question.id %}">{{ question.question_text }}</a>
                {% endfor %}
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <footer>
      Created by Thinh
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

pythonweb/moviepoll/templates/moviepoll/base_site.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Intek Friday Movie Night</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'moviepoll:index' %}"><img src="{% static "moviepoll/intek-logo.png" %}" width=10% class="img-fluid" alt="intek-logo"> Intek Institute</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'moviepoll:index' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#"  id="navbarDropdown" data-toggle="dropdown">Polls</a>
              <div class="dropdown-menu">
                {% for question in question_list %}
                    <a class="dropdown-item" href="{% url 'moviepoll:detail' question.id %}">{{ question.question_text }}</a>
                {% endfor %}
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

pythonweb/moviepoll/templates/moviepoll/detail.html
{% extends "moviepoll/base.html" %}
{% block content %}
  <div class="row">
    <div class="col-sm-12 mb-4 mt-4">
      <h2>{{ question.question_text }}</h2>
    </div>
  </div>
  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}


  {% if question.choice_set.all %}
      <form action="{% url 'moviepoll:result' question.id %}" method="post">

          {% csrf_token %}

          <div class=choices>
            {% for choice in question.choice_set.all %}
              <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
              <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
          </div>

          <div class="row">
            <div class="col-sm-12 mt-4">
              <input type="submit" class="btn btn-dark btn-outline-danger" value="Vote">
              <button type="button" class="btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Mymodal">View Result</button>
            </div>
          </div>

          <div id=Mymodal class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">{{ question.question_text }}</h5>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    {% for choice in question.choice_set.all %}
                      {{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}<br>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-dark btn-outline-danger" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

      </form>
  {% else %}
      No movie have been chosen!
  {% endif %}
{% endblock content %}

pythonweb/moviepoll/templates/moviepoll/index.html
{% extends "moviepoll/base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Intek Movie Friday Night</h1>
    <p class="lead">At Intek, we will have a movie night every friday to relax and have some fun because it's not all about coding!. The movie will be based on your vote, yes, YOURS.</p>
    <p class="lead">
      <a class="btn btn-dark btn-outline-danger" href="{% url 'moviepoll:poll' %}" role="button">Vote now</a>
    </p>
  </div>
{% endblock content %}

pythonweb/moviepoll/templates/moviepoll/poll.html
{% extends "moviepoll/base.html" %}
{% block content %}
  <div class="row">
    <div class="col-sm-12 mb-4 mt-4">
      {% if question_list %}
          <ul>
              {% for question in question_list %}
                  <li class="quest"><a href="{% url 'moviepoll:detail' question.id %}">{{ question.question_text }}</a></li>
              {% endfor %}
          </ul>
      {% else %}
          No movie yet<br>you can log in as admin to add movie
      {% endif %}
      </div>
    </div>
{% endblock content %}